name: ci
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2.9.1

      - name: Check
        run: |
          cargo check
